"""Account performance and protection components; data comes from owned APIs."""

CSS=r'''
.account-report-row{display:grid;grid-template-columns:minmax(100px,1.6fr) repeat(4,minmax(60px,1fr));gap:12px;padding:13px 0;border-top:1px solid var(--line);align-items:center;font-size:12px}
.account-report-row>*{min-width:0;overflow-wrap:anywhere}.account-report-row small{display:block;color:var(--mut);margin-bottom:5px}.account-report-toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:14px 0}
.account-protection-row{display:flex;gap:14px;justify-content:space-between;flex-wrap:wrap;padding:13px 0;border-top:1px solid var(--line)}
@media(max-width:620px){.account-report-row{grid-template-columns:repeat(2,minmax(0,1fr))}.account-report-row>b{grid-column:1/-1}.desk-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
'''

JS=r'''
var PAPER_REPORT_PERIOD='epoch',PAPER_REPORT_DAY='',PAPER_REPORT_LOAD=0,PAPER_REPORT_CURRENCY='INR';
function accountMoney(value){return typeof value==='number'&&Number.isFinite(value)?new Intl.NumberFormat(PAPER_REPORT_CURRENCY==='INR'?'en-IN':'en-US',{style:'currency',currency:PAPER_REPORT_CURRENCY,maximumFractionDigits:2}).format(value):'—';}
function accountNumber(value,unit){return typeof value==='number'&&Number.isFinite(value)?value.toFixed(unit==='R'?2:1)+(unit||''):'—';}
function accountGroup(title,groups){var keys=Object.keys(groups||{});return '<section class=desk-panel><h2>'+esc(title)+'</h2>'+(keys.length?keys.map(function(key){var s=groups[key];return '<div class=account-report-row><b>'+esc(key.replace(/_/g,' '))+'</b><div><small>Closed trades</small>'+esc(s.trades)+'</div><div><small>Net P&L</small>'+accountMoney(s.net_pnl)+'</div><div><small>Win rate</small>'+accountNumber(s.win_rate,'%')+'</div><div><small>Average R · '+esc(s.r_observations)+' observed</small>'+accountNumber(s.average_r,'R')+'</div></div>';}).join(''):'<p class=desk-note>No closed trades in this period.</p>')+'</section>';}
function personalReportHtml(report){PAPER_REPORT_CURRENCY=report.currency==='USD'?'USD':'INR';var b=report.book||{},period=PAPER_REPORT_PERIOD==='day'?'daily':'current_epoch',s=report[period]||{};
 var h='<section class=desk-panel><div class=desk-head><div><div class=desk-eyebrow>YOUR PAPER · ACTUAL FILLS</div><h2>Account performance</h2></div><span class=desk-status>'+esc(report.currency)+'</span></div><p class=desk-note>Current epoch · '+esc(report.epoch)+'</p>';
 h+='<div class=desk-metrics><div><small>Capital</small><b>'+accountMoney(b.budget)+'</b></div><div><small>Cash</small><b>'+accountMoney(b.cash)+'</b></div><div><small>Current equity</small><b>'+accountMoney(b.equity)+'</b></div><div><small>Open positions</small><b>'+esc(b.positions)+'</b></div></div>';
 if(!report.valuation_complete)h+='<p role=alert class=desk-note>Equity unavailable: current marks missing for '+esc((report.missing_marks||[]).join(', '))+'. Cash remains recorded.</p>';
 h+='<div class=account-report-toolbar><button class=desk-action onclick="PAPER_REPORT_PERIOD=\'epoch\';loadStats()" aria-pressed="'+(PAPER_REPORT_PERIOD==='epoch')+'">Current epoch</button><button class=desk-action onclick="PAPER_REPORT_PERIOD=\'day\';loadStats()" aria-pressed="'+(PAPER_REPORT_PERIOD==='day')+'">Selected day</button><label>Closed-trade date <input type=date value="'+esc(report.day)+'" onchange="PAPER_REPORT_DAY=this.value;PAPER_REPORT_PERIOD=\'day\';loadStats()"></label></div>';
 h+='<p>'+esc(s.trades||0)+' closed paper trades · net '+accountMoney(s.net_pnl)+'</p><p class=desk-note>Balance is the current snapshot. The selected date filters closed trades; research scenarios and broker orders are separate.</p>';
 if(!(report.current_epoch||{}).trades)h+='<p class=desk-note>No completed trades in this epoch. No win rate or profitability record is available.</p>';
 h+='</section>';return h+accountGroup('By sleeve',report[PAPER_REPORT_PERIOD==='day'?'by_sleeve':'by_sleeve_epoch'])+accountGroup('By entry regime',report[PAPER_REPORT_PERIOD==='day'?'by_regime':'by_regime_epoch']);}
var accountOldLoadStats=loadStats;
loadStats=function(){if(BOOK!=='mine')return accountOldLoadStats();var el=document.getElementById('statlist');if(!el)return;
 var token=++PAPER_REPORT_LOAD;el.innerHTML='<p role=status class=desk-empty>Loading your paper account…</p>';
 api('/v2/api/paper-performance?market='+encodeURIComponent(typeof MKT==='undefined'?'IN':MKT)+(PAPER_REPORT_DAY?'&day='+encodeURIComponent(PAPER_REPORT_DAY):'')).then(function(r){if(token!==PAPER_REPORT_LOAD||BOOK!=='mine')return;if(!r.ok)throw Error(r.j.error||r.j.detail||'Paper report unavailable');el.innerHTML=personalReportHtml(r.j);}).catch(function(e){if(token===PAPER_REPORT_LOAD&&BOOK==='mine')el.innerHTML='<section class=desk-panel role=alert><h2>Paper report unavailable</h2><p>'+esc(e.message)+'</p><button class=desk-action onclick="loadStats()">Retry</button></section>';});};
function protectionHealthHtml(health){var p=health.protection||{},rows=p.rows||[];var labels={app_only:'Application monitored · no broker stop',required:'Native stop required',submitting:'Submission outcome pending',unknown:'Unknown · reconciliation required',armed:'Broker trigger scheduled',triggered:'Exit triggered · verify fills',cancelling:'Cancellation pending',cancelled:'Cancellation confirmed',failed:'Protection failed',closed:'Position closed'};
 var h='<section class=desk-panel style="margin-top:18px"><div class=desk-eyebrow>YOUR BROKER · EXECUTION HEALTH</div><h2>Position protection</h2><p class=desk-note>A scheduled broker trigger is not a guaranteed fill. Uncertain stops block duplicate exits and new risk.</p>';
 h+=rows.length?rows.map(function(row){return '<div class=account-protection-row><div><b>'+esc(row.symbol)+'</b><p class=desk-note>'+esc(row.quantity)+' confirmed entry shares · stop '+deskMoney(row.stop)+'</p></div><span class="desk-status '+(['armed','closed','cancelled'].indexOf(row.state)<0?'warn':'')+'">'+esc(labels[row.state]||'Unrecognised status · review required')+'</span></div>';}).join(''):'<p class=desk-note>No recorded managed broker protection obligations. This does not certify an external broker account.</p>';
 var incidents=health.incidents||[];if(incidents.length)h+='<p role=alert>'+incidents.length+' unresolved execution incident(s)</p>'+incidents.map(function(i){return '<p class=desk-note>'+esc(i.code)+': '+esc(i.detail)+'</p>';}).join('');return h+'</section>';}
var accountOldRenderBroker=renderBroker;
renderBroker=function(){accountOldRenderBroker();var el=document.getElementById('brokerBox'),h=window.BRKHEALTH;if(el&&h&&BRK&&Number(h.owner_user_id)===Number(BRK.owner_user_id)){var details=document.createElement('div');details.innerHTML=protectionHealthHtml(h);el.appendChild(details);}};
var APPROVED_PAPER_PLANS={},APPROVED_REQUESTS={};
function approvedPlansHtml(data){var rows=data.plans||[];APPROVED_PAPER_PLANS={};rows.forEach(function(row){APPROVED_PAPER_PLANS[row.id]=row;});
 return '<section class=desk-panel><div class=desk-eyebrow>APPROVED PAPER OPPORTUNITIES</div><h2>Ready for account review</h2><p class=desk-note>Frozen approvals are separate from the research shortlist. Your account risk and current entry checks run again before any paper fill.</p>'+(rows.length?rows.map(function(row){var p=row.plan;return '<div class=account-protection-row><div><b>'+esc(p.symbol)+'</b><p class=desk-note>'+esc(p.sleeve)+' · '+esc(p.model_version)+' · '+esc(p.quantity)+' shares</p><p class=desk-note>Entry '+deskMoney(p.entry_low)+'–'+deskMoney(p.entry_high)+' · stop '+deskMoney(p.stop)+' · target '+deskMoney(p.target)+'</p></div><div><span class=desk-status>'+esc(row.status)+'</span>'+(row.status==='approved'?'<button class=desk-action data-approved-plan="'+esc(row.id)+'">Review paper buy</button>':'')+'</div></div>';}).join(''):'<p class=desk-note>No approved execution plans. Research ideas require separate strategy approval; eligibility alone cannot place orders.</p>')+'</section>';}
function loadApprovedPlans(){var root=document.getElementById('approvedPaperPlans');if(!root)return;root.innerHTML='<p role=status>Loading approved paper plans…</p>';
 api('/v2/api/approved-plans').then(function(r){if(!r.ok)throw Error(r.j.detail||'Approval data unavailable');root.innerHTML=approvedPlansHtml(r.j);root.querySelectorAll('[data-approved-plan]').forEach(function(button){button.addEventListener('click',function(){reviewApprovedPaper(button.dataset.approvedPlan);});});}).catch(function(e){root.innerHTML='<p role=alert>'+esc(e.message)+'</p>';});}
function reviewApprovedPaper(id){var row=APPROVED_PAPER_PLANS[id];if(!row||row.status!=='approved')return;var p=row.plan,dialog=document.getElementById('approvedPaperReview');
 if(!dialog){dialog=document.createElement('dialog');dialog.id='approvedPaperReview';dialog.className='desk-panel';dialog.setAttribute('aria-labelledby','approvedPaperHeading');document.body.appendChild(dialog);}
 dialog.innerHTML='<h2 id=approvedPaperHeading>Review paper buy · '+esc(p.symbol)+'</h2><p>Account: your paper book · '+esc(p.quantity)+' shares</p><p>Entry zone '+deskMoney(p.entry_low)+'–'+deskMoney(p.entry_high)+'</p><p>Stop '+deskMoney(p.stop)+' · target '+deskMoney(p.target)+'</p><p class=desk-note>Model '+esc(p.model_version)+'. Quote, regime, contract rules and account risk are checked again. This is simulated execution.</p><div class=account-report-toolbar><button class=desk-action id=approvedPaperCancel>Cancel</button><button class="desk-action primary" id=approvedPaperSubmit>Confirm paper buy</button></div><p role=status id=approvedPaperResult></p>';
 dialog.querySelector('#approvedPaperCancel').onclick=function(){dialog.close();};dialog.querySelector('#approvedPaperSubmit').onclick=function(){var button=this;button.disabled=true;
  var key=APPROVED_REQUESTS[id]||(APPROVED_REQUESTS[id]=(globalThis.crypto&&crypto.randomUUID?crypto.randomUUID():'paper-'+Date.now()+'-'+Math.random()));
  api('/v2/api/approved-orders',{method:'POST',body:JSON.stringify({plan_id:id,request_key:key})}).then(function(r){var message=dialog.querySelector('#approvedPaperResult');if(!r.ok){message.textContent=r.j.reason||r.j.error||r.j.detail||'Paper order refused';if(r.j.status==='rejected')delete APPROVED_REQUESTS[id];button.disabled=false;return;}message.textContent='Paper fill confirmed: '+r.j.qty+' shares at '+deskMoney(r.j.entry)+'. Application exit management active.';dialog.querySelector('#approvedPaperCancel').textContent='Close';loadApprovedPlans();loadPos();loadStats();}).catch(function(){dialog.querySelector('#approvedPaperResult').textContent='Outcome unavailable. Retry uses the same request identity.';button.disabled=false;});};dialog.showModal();}
var accountOldLoadIdeas=loadIdeas;
loadIdeas=function(){accountOldLoadIdeas();loadApprovedPlans();};
'''


def enhance(html):
    return html.replace('</head>','<style id="account-report-design">'+CSS+'</style></head>',1).replace(
        '<div id=ideasStrip>','<div id=approvedPaperPlans></div><div id=ideasStrip>',1).replace(
        'boot();setInterval(()=>{if(ME)',JS+'\nboot();setInterval(()=>{if(ME)',1)
