"""Product workspace; presentation only, reusing owned actions and API gates."""

CSS = r'''
:root{--inf:#3659db;--infb:#edf1ff;--bg:#f5f7fb;--line:#e1e6ef}
[data-theme=dark]{--inf:#92a9ff;--infb:#252e4c;--bg:#0d1320;--card:#151e2e;--surf:#151e2e;--line:#29364a}
.side{width:220px;padding:26px 16px}.side a.on{border-left:0;background:var(--infb)}.side .b{letter-spacing:-1.2px}
.main{padding:0 28px 70px;max-width:1600px}.home-grid{display:block!important}.home-rail{display:none!important}.fd-greet{margin:24px 0 18px}.fd-hi{font-size:30px}.top{padding:14px 0}.indexbar{font-size:12px;padding:12px 0}
.ws-head{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap;margin-bottom:18px}.ws-head h2{margin:4px 0;font-size:22px;letter-spacing:-.6px}.ws-kicker{font-size:10px;font-weight:700;letter-spacing:1.3px;color:var(--mut);text-transform:uppercase}
.ws-card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:22px;min-width:0}.ws-grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(260px,1fr);gap:18px;margin-top:18px}.ws-balance{font-size:40px;letter-spacing:-1.5px;font-weight:720;margin:14px 0 8px}.ws-sub{font-size:12px;color:var(--mut);line-height:1.6;margin:4px 0}.ws-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin-top:22px;padding-top:18px;border-top:1px solid var(--line)}.ws-metrics small{display:block;font-size:11px;color:var(--mut);margin-bottom:6px}.ws-metrics b{font-size:17px;overflow-wrap:anywhere}
.ws-pill{display:inline-block;padding:5px 9px;background:var(--infb);color:var(--inf);border-radius:6px;font-size:11px;font-weight:650}.ws-pill.warn{background:var(--dnb);color:var(--dn)}.ws-stages{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:18px 0}.ws-stage{background:var(--bg);border:1px solid var(--line);border-radius:10px;padding:14px}.ws-stage b{display:block;font-size:24px;margin:5px 0}.ws-stage span{font-size:11px;color:var(--mut)}.ws-alert{padding:12px 14px;border-left:3px solid var(--inf);background:var(--bg);border-radius:0 8px 8px 0;font-size:12px;line-height:1.7;margin-top:12px}.ws-alert.warn{border-color:var(--dn)}
.ws-research{margin-top:20px}.ws-stock{display:grid;grid-template-columns:minmax(140px,1fr) minmax(90px,.6fr) minmax(180px,2fr) auto;align-items:center;gap:16px;padding:15px 0;border-top:1px solid var(--line)}.ws-stock button.ws-symbol{border:0;background:none;padding:0;color:var(--hd);font-weight:700;text-align:left;cursor:pointer;font-size:14px}.ws-stock small{display:block;font-size:11px;color:var(--mut);margin-top:5px}.ws-reason{font-size:12px;color:var(--mut);line-height:1.5}.ws-rank{color:var(--inf);font-size:11px;font-weight:650}.ws-empty{padding:24px 0;color:var(--mut);font-size:13px;line-height:1.7}.ws-levels{display:flex;gap:18px;flex-wrap:wrap;margin-top:12px}.ws-levels span{font-size:11px;color:var(--mut)}.ws-levels b{color:var(--tx);font-weight:600;margin-left:5px}.ws-position{padding:16px 0;border-top:1px solid var(--line)}
.ideas-hero{margin:12px 0 22px;align-items:center}.ideas-hero h1{font-size:30px;letter-spacing:-1px}.ideas-hero p{font-size:13px}.ideas-account{min-width:250px;padding:18px;border-radius:12px}.ideas-desk{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:20px}.ideas-toolbar{padding-bottom:16px}.ideas-filters{gap:12px}.ideas-empty{padding:28px 18px;border:0;background:var(--bg);border-radius:10px}.ideas-empty b{font-size:17px}.ideas-empty p{font-size:12px}.ig-plan-grid{gap:16px}.ig-plan{border-radius:12px!important}.ig-how{font-size:12px}.ideas-context{font-size:11px}.idea-levels{background:var(--bg);border-radius:8px;padding:12px}.idea-card-actions button{min-height:44px}
#ideasHead:has(>details:only-child){padding:0;border:0;background:transparent}#ideasHead details{padding:10px 0}.sec{font-weight:650}.ordgrid{gap:16px}.prow{padding:18px 16px;border-bottom:1px solid var(--line)}.prow-sub{line-height:1.8}.ws-page-banner{margin:16px 0;padding:15px 18px;border:1px solid var(--line);border-radius:12px;background:var(--card);font-size:12px;color:var(--mut)}
#positions .seg:has(#sbpos){display:none}
@media(max-width:1000px){.ws-grid{grid-template-columns:1fr}.ws-stock{grid-template-columns:minmax(120px,1fr) 90px minmax(150px,1.5fr) auto}}
@media(max-width:859px){.main{padding:0 16px 90px}.ws-card{padding:18px 16px}.ws-head h2{font-size:20px}.ws-balance{font-size:35px}.ws-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.ws-stages{grid-template-columns:repeat(2,minmax(0,1fr))}.ws-stock{grid-template-columns:minmax(0,1fr) auto;gap:10px}.ws-stock .ws-reason{grid-column:1/-1;grid-row:2}.ws-stock>button:last-child{grid-column:2;grid-row:3}.ws-stock small{overflow-wrap:anywhere}.ideas-desk{padding:15px 12px}.ideas-hero h1{font-size:26px}.ideas-account{min-width:0;width:100%}.ideas-toolbar{gap:12px}.ideas-tabs{width:100%}.ideas-tabs button{flex:1;padding:12px 5px;font-size:12px}.ideas-filters{grid-template-columns:1fr 1fr!important}.ideas-filters input{grid-column:1/-1}.ws-head .desk-switch{width:100%}.ws-grid{gap:14px}.ws-page-banner{line-height:1.7}.fd-hi{font-size:26px}}
'''

JS = r'''
function wsCount(v){return v==null?'—':esc(v);}
function wsMetric(label,value){return '<div><small>'+esc(label)+'</small><b>'+value+'</b></div>';}
function wsWatch(w){
 var rows=w&&w.rows||[],stale=w&&w.status!=='current';
 return '<section class="ws-card ws-research"><div class=ws-head><div><div class=ws-kicker>Research watch · '+esc(w&&w.price_asof||'date unavailable')+'</div><h2>What the stock screen found</h2></div><span class="ws-pill '+(stale?'warn':'')+'">'+(stale?'Historical / unavailable':'Research only')+'</span></div><p class=ws-sub>Ranked evidence across the liquid NSE universe. Failed checks stay visible. These rows are not buy recommendations.</p>'
 +(rows.length?rows.map(function(r,i){return '<article class=ws-stock><div><span class=ws-rank>'+String(i+1).padStart(2,'0')+' · evidence score '+esc(r.score)+'</span><br><button class=ws-symbol data-symbol="'+esc(r.symbol)+'" onclick="stock(this.dataset.symbol,\'IN\')">'+esc(r.symbol)+'</button><small>'+esc(r.sector)+'</small></div><div>'+deskMoney(r.price)+'<small>'+(r.relative_volume==null?'Volume unavailable':esc(r.relative_volume)+'× volume')+'</small></div><div class=ws-reason>'+esc(r.reason)+'</div><button class=desk-action data-symbol="'+esc(r.symbol)+'" onclick="stock(this.dataset.symbol,\'IN\')">Research →</button></article>';}).join(''):'<div class=ws-empty>No readable ranked evidence. Check data coverage below before using this screen.</div>')+'</section>';
}
function wsPipeline(d){
 var s=d.stock_screen||{},p=d.paper_pipeline||{},o=p.orders||{},regime=(d.regime_state||{}).IN||'UNKNOWN';
 var health=(d.markets||[]).find(function(x){return x.market==='IN';})||{},risk=health.readiness||{};
 var paused=regime==='OFF'||regime==='UNKNOWN'||risk.halted,watch=d.research_watch||{},c=watch.coverage||{},source=d.execution_data||{};
 var why=risk.halted?risk.reason:regime==='OFF'?'Market trend is below the long-entry gate. Screening continues; new long orders wait.':regime==='UNKNOWN'?'A current completed-session regime reading is required.':'Qualified plans still require rebound confirmation, fresh exchange data and account risk approval.';
 return '<section class=ws-card><div class=ws-head><div><div class=ws-kicker>Screen → confirm → order → manage</div><h2>Paper automation</h2></div><span class="ws-pill '+(paused?'warn':'')+'">'+(paused?'Entries waiting':'Selective entries')+'</span></div><div class=ws-stages>'
 +[['Stocks checked',s.screened_count],['Evidence passes',s.status==='current'?s.evidence_passes:null],['Pending buys',p.status==='ok'?(o.pending||0):null],['Completed trades',p.completed]].map(function(x){return '<div class=ws-stage><span>'+x[0]+'</span><b>'+wsCount(x[1])+'</b></div>';}).join('')+'</div>'
 +'<div class="ws-alert '+(paused?'warn':'')+'"><b>'+esc(regime)+' regime</b> · '+esc(why)+'</div>'
 +'<p class=ws-sub>Paper worker: '+esc(p.worker||'unknown')+' · '+wsCount(p.exits)+' exits awaiting an exchange quote. Stops and targets remain managed when entries are paused.</p>'
 +'<div class="ws-alert '+(source.rules?'':'warn')+'">Execution data: '+esc(source.reason||'Not verified')+'<br>Exchange status: '+esc(source.session||'unavailable')+'.</div>'
 +(p.last_order?'<p class=ws-sub>Latest order: '+esc(p.last_order.symbol)+' · '+esc(p.last_order.status)+' · '+esc(p.last_order.reason)+'</p>':'<p class=ws-sub>No order activity recorded in this paper epoch.</p>')
 +'<details style="margin-top:16px"><summary>Data coverage & reasons</summary><div class=ws-metrics>'+wsMetric('Universe constituents',wsCount(s.universe_count))+wsMetric('Price evidence',wsCount(c.price))+wsMetric('Dated earnings',wsCount(c.earnings))+wsMetric('Delivery session',wsCount(c.participation))+'</div><p class=ws-sub>Prices through '+esc(s.price_asof||'unavailable')+' · screen '+esc(s.generated_at||'unavailable')+'. Coverage counts do not establish execution permission.</p>'+(s.rejections||[]).map(function(r){return '<p class=ws-sub>'+wsCount(r.count)+' stocks · '+esc(r.reason)+'</p>';}).join('')+'</details></section>';
}
renderDesk=function(d){
 DESK_DATA=d;REAL=d.real||null;MINE=d.mine||null;HERO=null;
 var house=(d.markets||[]).find(function(x){return x.market==='IN';})||{},selected=DESK_ACCOUNT==='house'?house:DESK_ACCOUNT==='broker'?d.real:d.mine,isBroker=DESK_ACCOUNT==='broker';
 var tabs=['mine','house','broker'].map(function(x){return '<button class="'+(DESK_ACCOUNT===x?'on':'')+'" onclick="deskAccount(\''+x+'\')">'+({mine:'My paper',house:'Strategy paper',broker:'Upstox'})[x]+'</button>';}).join('');
 var html='<section class=ws-card><div class=ws-head><div><div class=ws-kicker>'+(isBroker?'Broker account · real money':'Paper workspace · simulated money')+'</div><h2>'+({mine:'Your portfolio',house:'Strategy portfolio',broker:'Your Upstox portfolio'})[DESK_ACCOUNT]+'</h2></div><div class=desk-switch aria-label="Account view">'+tabs+'</div></div>';
 if(selected){html+='<div class=ws-balance>'+deskMoney(selected.equity)+'</div><p class=ws-sub>Total equity · '+deskMoney(isBroker?selected.unrealised:selected.overall_pnl)+' '+(isBroker?'unrealised P&L':'P&L this epoch')+'</p><div class=ws-metrics>'+wsMetric('Available cash',deskMoney(selected.cash))+wsMetric(isBroker?'Invested':'Starting capital',deskMoney(isBroker?selected.invested:selected.budget))+wsMetric('Open positions',wsCount(isBroker?selected.n_positions:selected.positions))+wsMetric(isBroker?'Mode':'Realised P&L',isBroker?'Live':deskMoney(selected.realised))+'</div>';}
 else html+='<div class=ws-empty>'+ (isBroker?'Upstox balances unavailable. Check your connection in Account.':'Personal paper account unavailable for this plan.')+'</div>';
 html+='</section><div class=ws-grid>'+wsPipeline(d)+'<section class=ws-card><div class=ws-head><div><div class=ws-kicker>Owned positions · paper</div><h2>Protection & activity</h2></div><button class=desk-action onclick="BOOK=\'mine\';go(\'orders\')">Orders →</button></div>';
 var held=d.mine&&d.mine.holdings||[];
 html+=held.length?held.map(function(p){return '<div class=ws-position><b>'+esc(p.symbol)+'</b> <span class=ws-sub>'+esc(p.shares)+' shares · '+esc(p.sleeve||p.strategy)+' · '+esc(p.regime||'Unknown regime')+'</span><div class=ws-levels><span>Stop<b>'+deskMoney(p.stop)+'</b></span><span>Target<b>'+deskMoney(p.target)+'</b></span><span>P&L<b>'+deskMoney(p.pnl)+'</b></span></div></div>';}).join(''):'<div class=ws-empty>No open personal paper positions.<br>Qualifying signals enter automatically after confirmation and account checks. Watching a stock does not place an order.</div>';
 html+='<button class="desk-action primary" onclick="go(\'ideas\')">Explore stock ideas →</button><p class=ws-sub style="margin-top:18px">Nifty 50 & Bank Nifty: market context and eligible products.</p><button class=desk-action onclick="go(\'indices\')">Index desk →</button></section></div>'+wsWatch(d.research_watch);
 document.getElementById('homefeed').innerHTML=html;
 document.getElementById('fd-hi').textContent='Your trading workspace';document.getElementById('fd-sub').textContent='NSE equities · selective research · automatic paper execution';
 var clock=document.getElementById('clock');if(clock)clock.textContent=d.as_of||'';
};
var wsOriginalIdeas=renderIdeas;
renderIdeas=function(d){wsOriginalIdeas(d);var target=document.getElementById('ideasList');if(!target)return;var watch=document.getElementById('workspaceResearch');if(watch)watch.remove();var box=document.createElement('div');box.id='workspaceResearch';target.after(box);box.innerHTML='<div class=ws-sub>Loading ranked research…</div>';
 var checks=document.getElementById('wsAccountChecks');if(!checks){checks=document.createElement('details');checks.id='wsAccountChecks';checks.className='ws-page-banner';checks.innerHTML='<summary>Account checks & approved paper orders</summary>';document.getElementById('ideas').appendChild(checks);}
 ['tradingReadiness','approvedPaperPlans'].forEach(function(id){var node=document.getElementById(id);if(node)checks.appendChild(node);});
 api('/v2/api/overview').then(function(r){if(!box.isConnected)return;box.innerHTML=r.ok?wsWatch(r.j.research_watch):'<div class=ws-alert>Research could not load. Retry the page.</div>';}).catch(function(){if(box.isConnected)box.innerHTML='<div class=ws-alert>Research connection interrupted. Retry the page.</div>';});};
var wsOriginalPos=posRow;
posRow=function(p){return '<div class=ws-owned-position>'+wsOriginalPos(p)+'<div class=ws-page-banner>'+esc(p.sleeve||p.strategy||'Manual')+' · '+esc(p.regime||'Regime unavailable')+' · Paper protection uses fresh exchange quotes; an exit request becomes a sale only after a fill.</div></div>';};
SUBPOS='all';
function wsPositionFilter(v){SUBPOS=v;renderPos();}
stratTag=function(st){return [({manual:'Manual',quality_momentum:'Quality momentum',mean_reversion:'Mean reversion',early_momentum:'Early momentum',index_directional:'Index directional',options_overlay:'Options overlay'})[st]||String(st||'Unknown').replace(/_/g,' '),'bg-inf'];};
renderPos=function(){
 var all=(Array.isArray(POS)?POS:[]).filter(function(p){return inMkt(p.market);}),rows=all.filter(function(p){return SUBPOS==='all'||(SUBPOS==='pos'?p.today:!p.today);});
 var total=all.reduce(function(sum,p){return sum+Number(p.pnl_amt||0);},0),root=document.getElementById('poslist');
 document.getElementById('postot').textContent=deskMoney(total)+' indicative open P&L';
 root.innerHTML='<div class=ws-head><div><h2>Open positions</h2><p class=ws-sub>All owned positions · stops, targets and exit status</p></div><div class=desk-switch>'+[['all','All'],['pos','Today'],['hold','Overnight']].map(function(x){return '<button class="'+(SUBPOS===x[0]?'on':'')+'" onclick="wsPositionFilter(\''+x[0]+'\')">'+x[1]+'</button>';}).join('')+'</div></div>'
 +(rows.length?rows.map(function(p){return '<article class="ws-card ws-position" style="margin-bottom:12px"><div class=ws-head><div><button class="desk-action ws-symbol" data-symbol="'+esc(p.symbol)+'" data-market="'+esc(p.market)+'" onclick="stock(this.dataset.symbol,this.dataset.market)">'+esc(p.symbol)+'</button><p class=ws-sub>'+esc(p.sleeve||p.strategy)+' · '+esc(p.regime||'Unknown')+' regime · '+esc(p.qty)+' shares</p></div><b>'+deskMoney(p.pnl_amt)+'</b></div><div class=ws-levels><span>Entry<b>'+deskMoney(p.entry)+'</b></span><span>Mark<b>'+deskMoney(p.live)+'</b></span><span>Stop-loss<b>'+deskMoney(p.stop)+'</b></span><span>Target<b>'+deskMoney(p.target)+'</b></span></div><p class=ws-sub>'+(p.quote_status==='fresh'?'Fresh quote':p.quote_status==='entry_only'?'No mark available; entry price shown':'Last recorded quote')+' · '+esc(p.quote_at||'timestamp unavailable')+'. Open P&L excludes estimated exit costs.</p><p class=ws-sub>Application paper protection · an exit request waits for a later executable bid.</p></article>';}).join(''):'<div class="ws-card ws-empty">'+(all.length?'No positions match this filter. Select All to see your holdings.':'No open paper positions. Check Ideas for qualifying plans and Orders for pending or rejected entries.')+'</div>');
};
loadPos=function(){var root=document.getElementById('poslist');root.innerHTML='<p role=status>Loading owned positions…</p>';api('/v2/api/positions?scope='+BOOK).then(function(r){if(!r.ok||!Array.isArray(r.j))throw Error();POS=r.j;renderPos();}).catch(function(){root.innerHTML='<div class=ws-alert role=alert>Positions could not load. Your holdings have not been cleared. Retry the page.</div>';});loadAttrib();loadPortfolio();};
ordRow=function(o){return '<div class=lrow><div class=ws-head style="margin:0"><div><b>'+esc(o.symbol)+'</b> <span class=ws-pill>'+esc(o.side)+'</span><p class=ws-sub>'+esc(o.qty)+' shares @ '+deskMoney(o.price)+' · '+esc(o.when||o.ts||'')+'</p></div><b>'+deskMoney(o.side==='SELL'?o.pnl_amt:o.value)+'</b></div><p class=ws-sub>'+esc(o.sleeve||o.strategy||'Manual')+' · '+esc(o.regime||'Unknown regime')+' · '+esc(o.status||o.reason||'Recorded fill')+'</p></div>';};
loadOrders=function(){var root=document.getElementById('ordlist');root.innerHTML='<p role=status>Loading owned paper orders…</p>';api('/v2/api/orders?limit=500&scope='+BOOK).then(function(r){if(!r.ok||!Array.isArray(r.j))throw Error();var rows=r.j.filter(function(o){return inMkt(o.market);}).filter(ordInRange);document.getElementById('ordtot').textContent=rows.length+' recorded fills in this period';root.innerHTML='<div id=paperPendingOrders aria-live=polite></div><section class=ws-card><div class=ws-head><div><h2>Filled order history</h2><p class=ws-sub>Paper fills · pending orders and research observations are separate</p></div></div>'+(rows.length?rows.map(ordRow).join(''):'<div class=ws-empty>No paper fills in this date range. Pending and rejected requests appear above.</div>')+'</section>';loadPaperOrders();}).catch(function(){root.innerHTML='<div class=ws-alert role=alert>Order history could not load. This is not an empty trading record. Retry the page.</div>';});};
'''


def enhance(html):
    # The legacy page has several style blocks. Product styles must follow all
    # of them; inserting into the first block silently loses the theme/layout.
    html = html.replace('</head>', '<style id=workspace-design>' + CSS + '</style></head>', 1)
    anchor = "boot();setInterval(()=>{if(ME)"
    if anchor not in html:
        raise ValueError('Workspace boot anchor missing')
    return html.replace(anchor, JS + '\n' + anchor, 1)
